### ISSUE TITLE
Add: Backend API to store quizes.

### ISSUE THREAD

**Issue by Qodestackr** [joelmuraguri/Learn#1]
Enjoyed the DSC Android Meetup. I could help build an API quickly with Django REST Framework that we could use to interact with, learn more CRUD functionality that comes with dynamic data, and data fetching with network clients in Kotlin.

A session on Retrofit would be great too.

**Comment by joelmuraguri** [comment]
Hi there!

Thanks for enjoying the GDSC Android Meetup and the Compose State Management talk! Your idea of building a Django REST Framework API for CRUD in Kotlin is great. The suggestion for a Retrofit session aligns perfectly  with dynamic data in Kotlin and will be considered for future discussions. Your input is appreciated, and I look forward to more insightful sessions ahead!
